### ISSUE TITLE
Dispatcher proto does not contain password

### ISSUE THREAD

**Issue by dias-bakhtiyarov** [Raccoon-AI/proto_schema#19]
Currently Dispatcher proto does not contain password field:

```proto
// GET => /v1/api/dispatcher/{id}
message Dispatcher {
  required uint64 id = 1;
  optional google.protobuf.Timestamp created_at = 2;
  required string phone_number = 3;
  required string email = 4;
  required string first_name = 6;
  optional string last_name = 7;
  optional uint64 telegram_id = 8;
  optional string telegram_username = 9;
  required uint64 company_id = 10;
}
```

This implies that it is currently impossible to do `proto` -> `DB` model conversion. You can only do `dict` -> `DB` directly, which bypasses pydantic validation. 

I feel like we need to decide upon what would be referred as a complete data representation format. 

Ideas:
- Create internal proto message that represents a complete data structure. (imho: Too much of a hassle)
- Add `password` field to proto message, but exclude it when sending this message. This is possible with pydantic: 
```python
return proto_obj.model_dump(exclude={'password'}
```

Any ideas?

Update:
Maybe we don't need a complete data representation...
When I create mock objects, I use base proto model, not `<Model>Create`. If I replace all mock object creations with `Create` models, this might solve the problem.

**Comment by olzhabay** [comment]
Yes, that was the idea behind using `Create` protobuf messages for creating objects
